apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
          - targets: ['192.168.59.109:30518']
      - job_name: 'app'
        scrape_interval: 5s
        static_configs:
          - targets: ['192.168.59.109:31274']